#!/usr/bin/env python3
"""check_parity.py — URL/alias/canonical/RSS/sitemap/OG/JSON-LD manifest diff.

specs/010 §2 · specs/007 §3.5 · issue #16

WHY THIS EXISTS
───────────────
Replacing the theme on a live archive is a URL migration wearing a redesign's
clothes. On the reference site (citizix.com) the post URLs themselves are safe —
499 of 500 posts pin their own `url:` in front matter and front matter is not
something a theme can change — so the naive check ("do the article URLs match?")
passes trivially and proves nothing.

Everything that CAN move is generated by the theme, and none of it is visible in a
screenshot:

    taxonomy URL shape          /tags/{term}/ and how terms are slugged
    pagination structure        /page/{n}/ on the home page, sections, terms AND
                                on the /tags/ + /categories/ browse pages
    /search/                    must keep existing at that exact path
    RSS                         feed paths AND the item <link> inside them
    canonical / og:url          per-page, template-generated
    JSON-LD mainEntityOfPage    per-page, template-generated
    sitemap <loc>               the reference site overrides layouts/sitemap.xml

So this compares two BUILT TREES, not two templates. It needs no Hugo, no network
and no third-party package (ADR-1 — a gate that needs a toolchain is a gate
contributors skip).

THE ALLOWLIST IS THE POINT
──────────────────────────
A theme swap that produced zero differences would mean the new theme was the old
theme. The deliverable is not "no differences", it is "every difference is
deliberate and written down". Reviewed differences live in a JSON file whose
REASON FIELD IS STRUCTURALLY MANDATORY — an empty reason is a hard failure, for
the same reason `.github/link-exclusions.json` works that way (docs/verification.md
§2): without a recorded reason, the next person tidying the file deletes a real
decision, or adds a rule to make CI green and nobody ever learns what moved.

USAGE
─────
    # diff two built trees
    python3 scripts/check_parity.py <baseline-public> <candidate-public> \
        --allow .github/parity/reviewed-differences.json

    # write one build's manifest out (for archiving, or diffing later)
    python3 scripts/check_parity.py --emit <public> --out manifest.json

    # diff two previously emitted manifests
    python3 scripts/check_parity.py --manifests base.json cand.json

    # build-wide invariants only — what .github/workflows/parity.yml asserts
    python3 scripts/check_parity.py --audit <public> \
        --expect-pages 1153 --expect-aliases 355

Exit status is 0 when every difference is reviewed, 1 otherwise.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from html.parser import HTMLParser
from xml.etree import ElementTree

# ── surfaces ────────────────────────────────────────────────────────────────────
# Order matters only for report readability. Each is diffed independently so a
# taxonomy change does not hide an RSS change behind it.
SURFACES = (
    "url",  # every HTML output URL that is a real page
    "alias",  # meta-refresh redirect  URL → target
    "canonical",  # <link rel=canonical>   URL → href
    "og_url",  # <meta property=og:url> URL → content
    "jsonld_main",  # JSON-LD mainEntityOfPage.@id   URL → @id
    "rss_feed",  # every RSS feed path
    "rss_item",  # feed path → ordered item <link> list
    "sitemap",  # every <loc> in sitemap.xml (or the sitemapindex's children)
)

_ALIAS_REFRESH = re.compile(r"^\s*0\s*;\s*url\s*=\s*(.+?)\s*$", re.I)


def rel_url(root: str, path: str) -> str:
    """Filesystem path inside a built tree → the URL a browser would request."""
    rel = os.path.relpath(path, root).replace(os.sep, "/")
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel


class _HeadScraper(HTMLParser):
    """Pulls the six per-page facts out of one HTML document.

    Written against MINIFIED output on purpose: `hugo --minify` drops attribute
    quotes, so `<link rel=canonical href=https://…/>` is what actually ships and a
    regex tuned to quoted attributes silently matches nothing. html.parser handles
    both, which is the whole reason this is not three regexes.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.canonical: str | None = None
        self.og_url: str | None = None
        self.refresh: str | None = None
        self.jsonld_blobs: list[str] = []
        self._in_ld = False
        self._buf: list[str] = []

    def handle_starttag(self, tag, attrs):
        a = {k.lower(): (v or "") for k, v in attrs}
        if tag == "link" and "canonical" in a.get("rel", "").lower().split():
            self.canonical = a.get("href")
        elif tag == "meta":
            if a.get("property", "").lower() == "og:url":
                self.og_url = a.get("content")
            elif a.get("http-equiv", "").lower() == "refresh":
                m = _ALIAS_REFRESH.match(a.get("content", ""))
                if m:
                    self.refresh = m.group(1)
        elif tag == "script" and a.get("type", "").strip().lower() == "application/ld+json":
            self._in_ld = True
            self._buf = []

    def handle_endtag(self, tag):
        if tag == "script" and self._in_ld:
            self.jsonld_blobs.append("".join(self._buf))
            self._in_ld = False
            self._buf = []

    def handle_data(self, data):
        if self._in_ld:
            self._buf.append(data)


def _main_entity(blobs: list[str]) -> str | None:
    """First `mainEntityOfPage` @id found in a page's JSON-LD, or None.

    Tolerant of a blob that will not parse: a broken JSON-LD block is a real defect
    but it belongs to scripts/check_jsonld.py, which asserts on the parsed VALUES.
    Failing here too would report one bug as two.
    """
    for blob in blobs:
        try:
            doc = json.loads(blob)
        except (ValueError, TypeError):
            continue
        for node in doc if isinstance(doc, list) else [doc]:
            if not isinstance(node, dict):
                continue
            meo = node.get("mainEntityOfPage")
            if isinstance(meo, dict) and meo.get("@id"):
                return meo["@id"]
            if isinstance(meo, str) and meo:
                return meo
    return None


def _localname(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def build_manifest(root: str) -> dict:
    """Walk a built tree once and return every parity surface."""
    root = os.path.abspath(root)
    if not os.path.isdir(root):
        sys.exit(f"check_parity: not a directory: {root}")

    urls: list[str] = []
    alias: dict[str, str] = {}
    canonical: dict[str, str] = {}
    og_url: dict[str, str] = {}
    jsonld_main: dict[str, str] = {}
    rss_item: dict[str, list[str]] = {}
    sitemap: list[str] = []

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            path = os.path.join(dirpath, name)
            if name.endswith(".html"):
                url = rel_url(root, path)
                with open(path, encoding="utf-8", errors="replace") as fh:
                    p = _HeadScraper()
                    try:
                        p.feed(fh.read())
                    except Exception as exc:  # a malformed page is a finding, not a crash
                        print(f"warn: {url}: {exc}", file=sys.stderr)
                if p.refresh:
                    # An alias is NOT an output URL. Conflating the two hides the
                    # case that matters: a URL that used to be a real page and is
                    # now a redirect, or the reverse.
                    alias[url] = p.refresh
                    continue
                urls.append(url)
                if p.canonical:
                    canonical[url] = p.canonical
                if p.og_url:
                    og_url[url] = p.og_url
                m = _main_entity(p.jsonld_blobs)
                if m:
                    jsonld_main[url] = m
            elif name.endswith(".xml"):
                url = rel_url(root, path)
                try:
                    tree = ElementTree.parse(path)
                except ElementTree.ParseError as exc:
                    print(f"warn: {url}: unparseable XML: {exc}", file=sys.stderr)
                    continue
                r = tree.getroot()
                kind = _localname(r.tag)
                if kind == "rss":
                    items = []
                    for it in r.iter():
                        if _localname(it.tag) != "item":
                            continue
                        for child in it:
                            if _localname(child.tag) == "link" and (child.text or "").strip():
                                items.append(child.text.strip())
                                break
                    rss_item[url] = items
                elif kind in ("urlset", "sitemapindex"):
                    for node in r.iter():
                        if _localname(node.tag) == "loc" and (node.text or "").strip():
                            sitemap.append(node.text.strip())

    return {
        "root": root,
        "url": sorted(urls),
        "alias": alias,
        "canonical": canonical,
        "og_url": og_url,
        "jsonld_main": jsonld_main,
        "rss_feed": sorted(rss_item),
        "rss_item": {k: v for k, v in sorted(rss_item.items())},
        "sitemap": sorted(set(sitemap)),
    }


# ── diffing ─────────────────────────────────────────────────────────────────────


class Difference:
    __slots__ = ("surface", "kind", "key", "base", "cand")

    def __init__(self, surface: str, kind: str, key: str, base=None, cand=None):
        self.surface, self.kind, self.key, self.base, self.cand = surface, kind, key, base, cand

    def line(self) -> str:
        if self.kind == "removed":
            return f"- {self.key}" + (f"  → {self.base}" if self.base not in (None, self.key) else "")
        if self.kind == "added":
            return f"+ {self.key}" + (f"  → {self.cand}" if self.cand not in (None, self.key) else "")
        return f"~ {self.key}\n      baseline:  {self.base}\n      candidate: {self.cand}"

    def as_dict(self) -> dict:
        return {"surface": self.surface, "kind": self.kind, "key": self.key,
                "baseline": self.base, "candidate": self.cand}


def diff_manifests(base: dict, cand: dict) -> list[Difference]:
    out: list[Difference] = []
    for surface in SURFACES:
        b, c = base.get(surface), cand.get(surface)
        if isinstance(b, list) and isinstance(c, list):
            bs, cs = set(b), set(c)
            out += [Difference(surface, "removed", k) for k in sorted(bs - cs)]
            out += [Difference(surface, "added", k) for k in sorted(cs - bs)]
        elif isinstance(b, dict) and isinstance(c, dict):
            for k in sorted(set(b) - set(c)):
                out.append(Difference(surface, "removed", k, base=b[k]))
            for k in sorted(set(c) - set(b)):
                out.append(Difference(surface, "added", k, cand=c[k]))
            for k in sorted(set(b) & set(c)):
                if b[k] != c[k]:
                    out.append(Difference(surface, "changed", k, base=b[k], cand=c[k]))
    return out


# ── the reviewed-differences file ───────────────────────────────────────────────


def load_rules(path: str) -> list[dict]:
    """Load and VALIDATE the allowlist.

    Every rule needs a non-empty `reason`. This is enforced structurally rather
    than by review because an unexplained allow-rule is indistinguishable from
    someone silencing a real regression, and six months later nobody can tell which
    it was. Same rule, same reasoning, as `.github/link-exclusions.json`.
    """
    if not path:
        return []
    if not os.path.exists(path):
        sys.exit(f"check_parity: allowlist not found: {path}")
    with open(path, encoding="utf-8") as fh:
        doc = json.load(fh)
    rules = doc.get("rules", doc if isinstance(doc, list) else [])
    for i, rule in enumerate(rules):
        where = f"{path} rule[{i}]"
        if rule.get("surface") not in SURFACES:
            sys.exit(f"{where}: surface must be one of {', '.join(SURFACES)}")
        if rule.get("kind") not in ("added", "removed", "changed"):
            sys.exit(f"{where}: kind must be added, removed or changed")
        if not str(rule.get("match", "")).strip():
            sys.exit(f"{where}: `match` (a regex against the key) is required")
        if not str(rule.get("reason", "")).strip():
            sys.exit(f"{where}: `reason` is REQUIRED and must not be empty — an "
                     f"unexplained allow-rule is indistinguishable from a silenced regression")
        try:
            re.compile(rule["match"])
        except re.error as exc:
            sys.exit(f"{where}: bad regex {rule['match']!r}: {exc}")
    return rules


def match_rule(diff: Difference, rules: list[dict]) -> dict | None:
    for rule in rules:
        if rule["surface"] != diff.surface or rule["kind"] != diff.kind:
            continue
        if not re.search(rule["match"], diff.key):
            continue
        # A `changed` rule may additionally constrain the new value, so "canonical
        # changed to something plausible" cannot be waved through as "canonical
        # changed to anything at all".
        expect = rule.get("candidate_match")
        if expect and not re.search(expect, str(diff.cand)):
            continue
        return rule
    return None


# ── build-wide invariants (what the CI smoke build asserts) ─────────────────────


def audit(root: str) -> dict:
    """Cheap build-wide assertions over an archive build.

    `lntable` is counted in HTML ONLY. Both palettes legitimately carry
    `.lntable` selectors so that a per-block `{linenos=true}` opt-in is styled, so
    a whole-tree grep reports 1 hit on a perfectly correct build and the assertion
    reads as broken. The claim being tested is that no PAGE emits the table.
    """
    root = os.path.abspath(root)
    stats = {"html_pages": 0, "aliases": 0, "lntable_pages": [], "bare_pre_pages": [],
             "code_blocks": 0, "chroma_blocks": 0}
    bare_pre = re.compile(r"<pre(?![^>]*class)[^>]*>\s*<code(?![^>]*class)", re.I)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            if not name.endswith(".html"):
                continue
            path = os.path.join(dirpath, name)
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
            url = rel_url(root, path)
            if 'http-equiv=refresh' in text.replace('"', "").replace(" =", "="):
                stats["aliases"] += 1
                continue
            stats["html_pages"] += 1
            if "lntable" in text:
                stats["lntable_pages"].append(url)
            if bare_pre.search(text):
                stats["bare_pre_pages"].append(url)
            stats["code_blocks"] += text.count('class="rb-code"') + text.count("class=rb-code ")
            stats["chroma_blocks"] += text.count('class="chroma"') + text.count("class=chroma>")
    return stats


# ── reporting ───────────────────────────────────────────────────────────────────


def report(diffs: list[Difference], rules: list[dict], verbose: bool) -> int:
    reviewed: dict[str, list[Difference]] = {}
    unreviewed: list[Difference] = []
    for d in diffs:
        rule = match_rule(d, rules)
        if rule:
            reviewed.setdefault(rule["reason"], []).append(d)
        else:
            unreviewed.append(d)

    print("PARITY MANIFEST DIFF")
    print("=" * 78)

    by_surface: dict[str, list[Difference]] = {}
    for d in unreviewed:
        by_surface.setdefault(d.surface, []).append(d)

    for surface in SURFACES:
        items = by_surface.get(surface)
        if not items:
            continue
        print(f"\n  UNREVIEWED — {surface}  ({len(items)})")
        for d in items[:40]:
            print("      " + d.line())
        if len(items) > 40:
            print(f"      … and {len(items) - 40} more")

    if reviewed:
        print(f"\n  REVIEWED ({sum(len(v) for v in reviewed.values())} differences, "
              f"{len(reviewed)} recorded reasons)")
        for reason, items in reviewed.items():
            surfaces = ", ".join(sorted({d.surface for d in items}))
            print(f"      {len(items):5d}  [{surfaces}]  {reason}")
            if verbose:
                for d in items[:20]:
                    print("             " + d.line().replace("\n", "\n         "))
                if len(items) > 20:
                    print(f"             … and {len(items) - 20} more")

    print("\n" + "=" * 78)
    if unreviewed:
        print(f"FAIL — {len(unreviewed)} unreviewed difference(s), "
              f"{sum(len(v) for v in reviewed.values())} reviewed")
        print("       Either eliminate the difference, or add a rule WITH A REASON to the "
              "allowlist.")
        return 1
    print(f"PASS — 0 unreviewed differences, "
          f"{sum(len(v) for v in reviewed.values())} reviewed and recorded")
    return 0


def summarise(m: dict, label: str) -> None:
    print(f"  {label:10s} urls={len(m['url']):5d}  aliases={len(m['alias']):4d}  "
          f"canonical={len(m['canonical']):5d}  og:url={len(m['og_url']):5d}  "
          f"jsonld={len(m['jsonld_main']):5d}  feeds={len(m['rss_feed']):4d}  "
          f"rss-items={sum(len(v) for v in m['rss_item'].values()):6d}  "
          f"sitemap={len(m['sitemap']):5d}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("baseline", nargs="?", help="built tree of the theme being replaced")
    ap.add_argument("candidate", nargs="?", help="built tree of Runbook")
    ap.add_argument("--emit", metavar="DIR", help="write one build's manifest and exit")
    ap.add_argument("--out", metavar="FILE", help="destination for --emit (default: stdout)")
    ap.add_argument("--manifests", nargs=2, metavar=("BASE", "CAND"),
                    help="diff two previously emitted manifest files")
    ap.add_argument("--audit", metavar="DIR", help="build-wide invariants over one tree")
    ap.add_argument("--expect-pages", type=int, help="--audit: required HTML page count")
    ap.add_argument("--expect-aliases", type=int, help="--audit: required alias count")
    ap.add_argument("--allow", metavar="FILE",
                    default=".github/parity/reviewed-differences.json",
                    help="reviewed-differences file (default: %(default)s)")
    ap.add_argument("--no-allow", action="store_true", help="ignore the allowlist entirely")
    ap.add_argument("--json", metavar="FILE", help="also write the diff as JSON")
    ap.add_argument("-v", "--verbose", action="store_true", help="list reviewed differences too")
    args = ap.parse_args()

    if args.audit:
        stats = audit(args.audit)
        print("ARCHIVE BUILD AUDIT")
        print("=" * 78)
        print(f"  HTML pages          {stats['html_pages']}")
        print(f"  aliases             {stats['aliases']}")
        print(f"  rb-code blocks      {stats['code_blocks']}")
        print(f"  chroma blocks       {stats['chroma_blocks']}")
        print(f"  pages with lntable  {len(stats['lntable_pages'])}")
        print(f"  pages with bare pre {len(stats['bare_pre_pages'])}")
        failed = False
        if stats["lntable_pages"]:
            failed = True
            print("\nFAIL — REQ-CB-1: a page emitted <table class=lntable>:")
            for u in stats["lntable_pages"][:20]:
                print("      " + u)
        if args.expect_pages is not None and stats["html_pages"] != args.expect_pages:
            failed = True
            print(f"\nFAIL — page count {stats['html_pages']} != expected {args.expect_pages}")
        if args.expect_aliases is not None and stats["aliases"] != args.expect_aliases:
            failed = True
            print(f"\nFAIL — alias count {stats['aliases']} != expected {args.expect_aliases}")
        if stats["bare_pre_pages"]:
            # Advisory: a bare <pre><code> is REQ-CB-8's styling path, which is a
            # supported state. It is reported because a JUMP in the count means a
            # render hook stopped firing.
            print(f"\nNOTE — {len(stats['bare_pre_pages'])} page(s) contain a bare "
                  f"<pre><code>; that is REQ-CB-8's supported path, not a failure. "
                  f"First few: {', '.join(stats['bare_pre_pages'][:3])}")
        print("\n" + "=" * 78)
        print("FAIL" if failed else "PASS")
        return 1 if failed else 0

    if args.emit:
        m = build_manifest(args.emit)
        text = json.dumps(m, indent=2, sort_keys=True)
        if args.out:
            with open(args.out, "w", encoding="utf-8") as fh:
                fh.write(text + "\n")
            summarise(m, "manifest")
            print(f"  written to {args.out}")
        else:
            print(text)
        return 0

    if args.manifests:
        with open(args.manifests[0], encoding="utf-8") as fh:
            base = json.load(fh)
        with open(args.manifests[1], encoding="utf-8") as fh:
            cand = json.load(fh)
    elif args.baseline and args.candidate:
        base = build_manifest(args.baseline)
        cand = build_manifest(args.candidate)
    else:
        ap.error("give two built trees, or --manifests BASE CAND, or --emit DIR, or --audit DIR")

    print("BUILD MANIFESTS")
    print("=" * 78)
    summarise(base, "baseline")
    summarise(cand, "candidate")
    print()

    rules = [] if args.no_allow else load_rules(args.allow)
    diffs = diff_manifests(base, cand)

    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump([d.as_dict() for d in diffs], fh, indent=2)

    return report(diffs, rules, args.verbose)


if __name__ == "__main__":
    sys.exit(main())
